/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model() {
  const { nodes, materials } = useGLTF('../../../public/models/demo_scene.glb')
  return (
    <group dispose={null}>
      <group position={[-8.31, 0, -10.86]} rotation={[Math.PI, 0, Math.PI]} scale={0.02}>
        <mesh geometry={nodes.object1.geometry} material={materials.default_material} />
        <mesh geometry={nodes.object2.geometry} material={materials.default_material} />
        <mesh geometry={nodes.object3.geometry} material={materials.default_material} />
        <mesh geometry={nodes.object4.geometry} material={materials['�������� �4']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[5, 0, 0]} scale={[20, 10, 20]} />
      <mesh geometry={nodes.Mesh.geometry} material={materials['Material.001']} position={[-2.45, 4.77, -11.64]} rotation={[Math.PI / 2, 0, 1.74]} scale={0.03} />
      <mesh geometry={nodes.Mesh001.geometry} material={materials['Material.001']} position={[23.93, 4.77, -8.56]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Mesh002.geometry} material={materials['Material.001']} position={[23.93, 4.77, 14.39]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Mesh003.geometry} material={materials['Material.001']} position={[-14.07, 4.77, 14.39]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Mesh004.geometry} material={materials['Material.001']} position={[-1.07, 4.77, 14.39]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Mesh005.geometry} material={materials['Material.001']} position={[11.93, 4.77, 14.39]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[5.81, 1.4, -17.96]} rotation={[0, -0.06, 0]} scale={0.84} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[5.82, 1.4, -17.93]} rotation={[0, -0.06, 0]} scale={0.84} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[19.83, 3.88, -13.56]} scale={[1.9, 3.35, 1.9]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[24, 4, -18]} scale={[1, 4, 8]} />
      <mesh geometry={nodes.Aset_container_other_M_ufghbgyfa_00_LOD5.geometry} material={nodes.Aset_container_other_M_ufghbgyfa_00_LOD5.material} position={[5.61, 0.05, -12.27]} rotation={[0.45, -0.54, -0.82]} scale={0.04} />
      <mesh geometry={nodes.Aset_container_other_M_ufghbgyfa_01_LOD5.geometry} material={nodes.Aset_container_other_M_ufghbgyfa_01_LOD5.material} position={[5.66, 0, -13.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes.Aset_interior_door_M_wbdjcihdw_LOD5.geometry} material={materials['default_material.002']} position={[22.88, 0, -20.01]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-5, 5, -20]} scale={[10, 5, 6]} />
      <mesh geometry={nodes.Aset_building_window_M_vmhmaardw_LOD5.geometry} material={materials['default_material.003']} position={[5.01, 2.16, -23.9]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_building_window_M_vmhmaardw_LOD5002.geometry} material={materials['default_material.003']} position={[1.94, 12.04, -23.75]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_building_window_M_vmhmaardw_LOD5003.geometry} material={materials['default_material.003']} position={[1.94, 12.04, -18.61]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_building_window_M_vmhmaardw_LOD5001.geometry} material={materials['default_material.003']} position={[-0.47, 12.04, -16.42]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Aset_building_window_M_vmhmaardw_LOD5004.geometry} material={materials['default_material.003']} position={[-6.48, 12.04, -16.42]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Aset_building_window_M_vmhmaardw_LOD5005.geometry} material={materials['default_material.003']} position={[-12.47, 12.04, -16.42]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Aset_building_combined_L_wdetbjudw_00_LOD5.geometry} material={materials['default_material.004']} position={[24.98, 0, 19.59]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.02} />
      <mesh geometry={nodes.Aset_building_combined_L_wdetbjudw_02_LOD5.geometry} material={materials['default_material.004']} position={[17.01, 0, 19.59]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.02} />
      <mesh geometry={nodes.Aset_building_combined_L_wdetbjudw_03_LOD5.geometry} material={materials['default_material.004']} position={[9.04, 0, 19.59]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.02} />
      <mesh geometry={nodes.Aset_building_combined_L_wdetbjudw_00_LOD5001.geometry} material={materials['default_material.004']} position={[1.07, 0, 19.59]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.02} />
      <mesh geometry={nodes.Aset_building_combined_L_wdetbjudw_00_LOD5002.geometry} material={materials.default_material} position={[-6.9, 0, 19.59]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.02} />
    </group>
  )
}

useGLTF.preload('../../../public/models/demo_scene.glb')

export default Model;
