/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function DemoScene2() {
  const { nodes, materials } = useGLTF('./models/demo_scene_2_no_texture_compressed.glb')
  return (
    <group castShadow dispose={null}>
      <group position={[20.78, 5.52, -0.03]} rotation={[0, -1.48, -Math.PI / 2]} scale={0.04}>
        <mesh geometry={nodes.Cylinder005001.geometry} material={materials.Iron_se4objgc} position={[0, -0.21, 1.39]} rotation={[-1.4, 0, 0]} scale={0.49} />
      </group>
      <group position={[20.81, 5.52, 3.31]} rotation={[0, -1.48, -Math.PI / 2]} scale={0.04}>
        <mesh geometry={nodes.Cylinder009.geometry} material={materials.Iron_se4objgc} position={[0, -0.21, 1.39]} rotation={[-1.4, 0, 0]} scale={0.49} />
      </group>
      <group position={[20.78, 3.52, -0.03]} rotation={[0, -1.48, -Math.PI / 2]} scale={0.04}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Iron_se4objgc} position={[0, -0.21, 1.39]} rotation={[-1.4, 0, 0]} scale={0.49} />
      </group>
      <group position={[20.8, 3.52, 3.32]} rotation={[0, -1.48, -Math.PI / 2]} scale={0.04}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials.Iron_se4objgc} position={[0, -0.21, 1.39]} rotation={[-1.4, 0, 0]} scale={0.49} />
      </group>
      <mesh geometry={nodes.wPlane001.geometry} material={materials.Patterned_Stone_vjqqcck} scale={30} />
      <group position={[-0.74, -0.02, 21.94]} rotation={[Math.PI / 2, 0, 0]} scale={0.13}>
        <mesh castShadow geometry={nodes.Mesh001.geometry} material={materials['Wood.002']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Red_Metal.002']} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials['Wood_2.002']} />
        <mesh geometry={nodes.Mesh001_3.geometry} material={materials['Lamp.002']} />
        <mesh geometry={nodes.Mesh001_4.geometry} material={materials['Grill.002']} />
        <mesh geometry={nodes.Mesh001_5.geometry} material={materials['Lamp_2.002']} />
      </group>
      <mesh geometry={nodes.ads.geometry} material={materials['M_placeholder.001']} position={[-10.08, 15.23, 21.32]} rotation={[Math.PI / 2, 0, 0]} scale={0.13} />
      <mesh geometry={nodes.wPlane.geometry} material={materials.M_placeholder} position={[-29.95, 10, 0]} rotation={[0, 0, Math.PI / 2]} scale={[10, 1, 30]} />
      <mesh geometry={nodes.slab_of_wood.geometry} material={materials.M_Scaffholding_Wood} position={[12.13, 6.86, 17.34]} scale={4.16} />
      <mesh geometry={nodes.slab_of_wood001.geometry} material={materials.M_Scaffholding_Wood} position={[12.13, 8.52, 17.34]} rotation={[Math.PI, 0, Math.PI]} scale={4.16} />
      <mesh geometry={nodes.steel_scaffolding.geometry} material={materials.M_Scaffholding} position={[12.13, -0.01, 17.34]} scale={4.16} />
      <mesh geometry={nodes.Box02.geometry} material={materials['M_placeholder.002']} position={[7.65, 2.7, 6.53]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cylinder01.geometry} material={materials.M_Metal_Billboard_2} position={[6.35, 3.7, 6.58]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder02.geometry} material={materials.M_Metal_Billboard_2} position={[6.35, 2.7, 6.58]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder03.geometry} material={materials.M_Metal_Billboard_2} position={[6.35, 1.7, 6.58]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.M_Metal_Billboard_2} position={[8.95, 3.7, 6.58]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.M_Metal_Billboard_2} position={[8.95, 2.7, 6.58]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.M_Metal_Billboard_2} position={[8.95, 1.7, 6.58]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Rectangle01.geometry} material={materials.M_Metal_Billboard_2} position={[7.65, 2.1, 6.58]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rectangle02.geometry} material={materials.M_Metal_Billboard} position={[7.65, 2.7, 6.38]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Box01.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 0, 10.54]} />
      <mesh geometry={nodes.Box02001.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 0, 10.54]} />
      <mesh geometry={nodes.Box03.geometry} material={materials['M_Metal_Billboard_2.001']} position={[-2.05, 5.7, 10.39]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Box04.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 3.95, 10.54]} />
      <mesh geometry={nodes.Box05.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 2.67, 10.54]} />
      <mesh geometry={nodes.Box06.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 1.39, 10.54]} />
      <mesh geometry={nodes.Box07.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 4, 10.54]} rotation={[0, 0, -Math.PI]} />
      <mesh geometry={nodes.Box08.geometry} material={materials['M_placeholder.003']} position={[-2.05, 5.7, 10.37]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Rectangle01001.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 5.7, 10.39]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Rectangle02001.geometry} material={materials['M_Metal_Billboard.001']} position={[-2.05, 5.7, 10.69]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[18.63, 0.65, -9.04]} rotation={[0, -1.57, 0]} scale={0.08}>
        <mesh geometry={nodes.Mesh021.geometry} material={materials.Metal_paint_grey} />
        <mesh geometry={nodes.Mesh021_1.geometry} material={materials['Supergloss Jet Black']} />
        <mesh geometry={nodes.Mesh021_2.geometry} material={materials.ADV_poster} />
      </group>
      <mesh geometry={nodes.ADV_BOX_FOOT.geometry} material={materials['Supergloss Jet Black']} position={[18.64, -0.03, -9.04]} rotation={[0, -1.57, 0]} scale={[0.09, 0.07, 0.18]} />
      <mesh geometry={nodes.Back_joint_small.geometry} material={materials.Iron_se4objgc} position={[20.6, 6.69, -10.03]} rotation={[-Math.PI / 2, 0, 0.01]} scale={[-0.1, -0.33, -0.1]} />
      <mesh geometry={nodes.Bench.geometry} material={materials.Steel_se4nad3c} position={[19.89, 1.3, -0.51]} rotation={[0, -1.57, 0]} scale={[0.08, 0.04, 0.08]} />
      <mesh geometry={nodes.Bench_bolt1.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.38, 1.34, -4.32]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt2.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.13, 1.34, -4.32]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt3.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[19.87, 1.34, -4.32]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt4.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.4, 1.34, -0.95]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt5.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.15, 1.34, -0.95]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt6.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[19.89, 1.34, -0.95]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt7.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.41, 1.34, -0.05]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt8.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.15, 1.34, -0.05]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt9.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[19.89, 1.34, -0.05]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt10.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.43, 1.34, 3.32]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt11.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[20.17, 1.34, 3.32]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_bolt12.geometry} material={materials.Brushed_Aluminum_shkaaafc} position={[19.91, 1.34, 3.32]} rotation={[0, -1.57, 0]} scale={[0.03, 0.01, 0.03]} />
      <mesh geometry={nodes.Bench_holder_left.geometry} material={materials['Supergloss Jet Black.005']} position={[20.17, 1.19, -4.76]} rotation={[0, -1.57, 0]} scale={[0.13, 0.17, 0.26]} />
      <mesh geometry={nodes.Bench_holder_middle.geometry} material={materials['Supergloss Jet Black.005']} position={[20.2, 1.19, -0.49]} rotation={[0, -1.57, 0]} scale={[0.13, 0.17, 0.26]} />
      <mesh geometry={nodes.Bench_holder_right.geometry} material={materials['Supergloss Jet Black.005']} position={[20.22, 1.19, 3.78]} rotation={[0, -1.57, 0]} scale={[0.13, 0.17, 0.26]} />
      <mesh geometry={nodes.Bench_joint1.geometry} material={materials['Supergloss Jet Black.008']} position={[20.13, 1.28, -4.65]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint2.geometry} material={materials['Supergloss Jet Black.012']} position={[20.13, 1.28, -4.31]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint3.geometry} material={materials['Supergloss Jet Black.013']} position={[20.13, 1.28, -3.64]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint4.geometry} material={materials['Supergloss Jet Black.014']} position={[20.14, 1.28, -2.96]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint5.geometry} material={materials['Supergloss Jet Black.015']} position={[20.14, 1.28, -2.29]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint6.geometry} material={materials['Supergloss Jet Black.016']} position={[20.14, 1.28, -1.61]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint7.geometry} material={materials['Supergloss Jet Black.017']} position={[20.15, 1.28, -0.94]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint8.geometry} material={materials['Supergloss Jet Black.009']} position={[20.15, 1.28, -0.59]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint9.geometry} material={materials['Supergloss Jet Black.010']} position={[20.15, 1.28, -0.38]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint10.geometry} material={materials['Supergloss Jet Black.023']} position={[20.15, 1.28, -0.05]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint11.geometry} material={materials['Supergloss Jet Black.022']} position={[20.16, 1.28, 0.63]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint12.geometry} material={materials['Supergloss Jet Black.021']} position={[20.16, 1.28, 1.3]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint13.geometry} material={materials['Supergloss Jet Black.020']} position={[20.16, 1.28, 1.98]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint14.geometry} material={materials['Supergloss Jet Black.019']} position={[20.17, 1.28, 2.65]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint15.geometry} material={materials['Supergloss Jet Black.018']} position={[20.17, 1.28, 3.33]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Bench_joint16.geometry} material={materials['Supergloss Jet Black.011']} position={[20.17, 1.28, 3.67]} rotation={[0, -1.57, 0]} scale={[0.08, 0.08, 0.07]} />
      <mesh geometry={nodes.Front_joint_main.geometry} material={materials.Iron_se4objgc} position={[16.85, 6.69, 5.01]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.1, 0.33, 0.1]} />
      <mesh geometry={nodes.Front_joint_small.geometry} material={materials.Metal_paint_grey} position={[16.95, 6.48, -2.62]} rotation={[Math.PI / 2, 0, 1.57]} scale={0.08} />
      <mesh geometry={nodes.glass_holder1.geometry} material={materials.Steel_se4nad3c} position={[20.67, 5.63, -8.87]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder2.geometry} material={materials.Steel_se4nad3c} position={[20.69, 5.63, -4.97]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder3.geometry} material={materials.Steel_se4nad3c} position={[20.67, 0.77, -8.87]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder4.geometry} material={materials.Steel_se4nad3c} position={[20.69, 0.77, -4.97]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder5.geometry} material={materials.Steel_se4nad3c} position={[20.69, 5.63, -4.57]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder6.geometry} material={materials.Steel_se4nad3c} position={[20.69, 0.77, -4.57]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder7.geometry} material={materials.Iron_se4objgc} position={[20.71, 5.63, -0.69]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder8.geometry} material={materials.Steel_se4nad3c} position={[20.71, 0.77, -0.69]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder9.geometry} material={materials.Iron_se4objgc} position={[20.71, 5.63, -0.28]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder10.geometry} material={materials.Steel_se4nad3c} position={[20.71, 0.77, -0.28]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder11.geometry} material={materials.Steel_se4nad3c} position={[20.73, 5.63, 3.6]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.glass_holder12.geometry} material={materials.Steel_se4nad3c} position={[20.73, 0.77, 3.6]} rotation={[0, -1.57, 0]} scale={[0.03, 0.03, 0.02]} />
      <mesh geometry={nodes.Glass_wall1.geometry} material={materials['Window (Interior/Exterior)']} position={[20.71, 0.6, -6.9]} rotation={[Math.PI, -0.01, Math.PI]} scale={0.08} />
      <mesh geometry={nodes.Glass_wall2.geometry} material={materials['Window (Interior/Exterior)']} position={[20.74, 0.6, -2.63]} rotation={[Math.PI, -0.01, Math.PI]} scale={0.08} />
      <mesh geometry={nodes.Glass_wall3.geometry} material={materials['Window (Interior/Exterior)']} position={[20.76, 0.6, 1.66]} rotation={[Math.PI, -0.01, Math.PI]} scale={0.08} />
      <group position={[20.76, 4.53, 1.65]} rotation={[Math.PI / 2, 0, 1.57]} scale={[0.08, 0.03, 0.12]}>
        <mesh geometry={nodes.Mesh071.geometry} material={materials.ADV_poster} />
        <mesh geometry={nodes.Mesh071_1.geometry} material={materials.Iron_se4objgc} />
        <mesh geometry={nodes.Mesh071_2.geometry} material={materials.Steel_se4nad3c} />
      </group>
      <mesh geometry={nodes.Left_joist.geometry} material={materials['Supergloss Jet Black.003']} position={[20.73, 2.87, -9.05]} rotation={[Math.PI / 2, 0, 1.57]} scale={[0.09, 0.25, 0.08]} />
      <mesh geometry={nodes.Right_joist.geometry} material={materials['Supergloss Jet Black.004']} position={[20.8, 2.87, 3.78]} rotation={[Math.PI / 2, 0, 1.57]} scale={[0.09, 0.25, 0.08]} />
      <mesh geometry={nodes.Roof.geometry} material={materials['Window (Interior/Exterior)']} position={[18.79, 2.74, 5.02]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.08, 5.02, 0.08]} />
      <mesh geometry={nodes.Roof_joist1.geometry} material={materials.Iron_se4objgc} position={[18.71, 2.74, -9.86]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.08, 0.05, 0.08]} />
      <mesh geometry={nodes.Roof_joist2.geometry} material={materials.Iron_se4objgc} position={[18.72, 2.74, -8.98]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.08, 0.05, 0.08]} />
      <mesh geometry={nodes.Roof_joist3.geometry} material={materials.Iron_se4objgc} position={[18.74, 2.74, -4.69]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.08, 0.05, 0.08]} />
      <mesh geometry={nodes.Roof_joist4.geometry} material={materials.Iron_se4objgc} position={[18.76, 2.74, -0.41]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.08, 0.05, 0.08]} />
      <mesh geometry={nodes.Roof_joist5.geometry} material={materials.Iron_se4objgc} position={[18.79, 2.74, 3.86]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.08, 0.05, 0.08]} />
      <mesh geometry={nodes.Roof_joist6.geometry} material={materials.Iron_se4objgc} position={[18.79, 2.74, 4.93]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.08, 0.05, 0.08]} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials.Iron_se4objgc} position={[20.78, 1.27, -0.49]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[0.05, 0.02, 0.05]} />
      <mesh geometry={nodes.Sphere014.geometry} material={materials.Iron_se4objgc} position={[20.8, 1.27, 3.78]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[0.05, 0.02, 0.05]} />
      <mesh geometry={nodes.Sphere015.geometry} material={materials.Iron_se4objgc} position={[20.76, 1.27, -4.77]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[0.05, 0.02, 0.05]} />
      <mesh geometry={nodes.Wall_joint1.geometry} material={materials['Supergloss Jet Black.006']} position={[20.75, 2.86, -4.77]} rotation={[Math.PI / 2, 0, 1.57]} scale={[0.09, 0.09, 0.08]} />
      <mesh geometry={nodes.Wall_joint2.geometry} material={materials['Supergloss Jet Black.002']} position={[20.77, 2.86, -0.48]} rotation={[Math.PI / 2, 0, 1.57]} scale={[0.09, 0.09, 0.08]} />
    </group>
  )
}

useGLTF.preload('./models/demo_scene_2_no_texture_compressed.glb')
