/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StreetSceneCompressed() {
  const { nodes, materials } = useGLTF('/models/final_scene_5.glb')
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Bus_Street.geometry} material={materials.Bus_Stop} position={[4, 0, 4]} scale={[1, 1, 4]} />
      <group position={[10.43, 0.09, -10.69]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01}>
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5.geometry} material={materials.Modular_Building_Ground_Floor_vdipcdadw} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5_1.geometry} material={materials.Modular_Building_Ground_Floor_Corner_vdirfa3dw} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5_2.geometry} material={materials.Modular_Building_3rd_Floor_vdiwfgydw} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5_3.geometry} material={materials.Modular_Building_Trim_vdjhfg2dw} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5_4.geometry} material={materials.Modular_Building_Roof_vdjxacjdw} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5_5.geometry} material={materials.Modular_Building_Gable_vdjlfgodw} />
      </group>
      <mesh geometry={nodes.Pavement.geometry} material={materials.Decorative_Stone_vizmbar} position={[13, 0.09, 0]} scale={[10, 1, 30]} />
      <mesh geometry={nodes.Street.geometry} material={materials.Street} scale={[3, 1, 30]} />
      <group position={[6.82, 0.31, 1.48]} rotation={[0, -1.57, 0]} scale={0.03}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials['Metal_paint_grey.002']} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials['Supergloss Jet Black.044']} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials['ADV_poster.002']} />
        <mesh geometry={nodes.Mesh003_3.geometry} material={materials['Iron_se4objgc.002']} />
        <mesh geometry={nodes.Mesh003_4.geometry} material={materials['Steel_se4nad3c.002']} />
        <mesh geometry={nodes.Mesh003_5.geometry} material={materials['Brushed_Aluminum_shkaaafc.002']} />
        <mesh geometry={nodes.Mesh003_6.geometry} material={materials['Supergloss Jet Black.045']} />
        <mesh geometry={nodes.Mesh003_7.geometry} material={materials['Supergloss Jet Black.046']} />
        <mesh geometry={nodes.Mesh003_8.geometry} material={materials['Supergloss Jet Black.047']} />
        <mesh geometry={nodes.Mesh003_9.geometry} material={materials['Supergloss Jet Black.048']} />
        <mesh geometry={nodes.Mesh003_10.geometry} material={materials['Supergloss Jet Black.049']} />
        <mesh geometry={nodes.Mesh003_11.geometry} material={materials['Supergloss Jet Black.050']} />
        <mesh geometry={nodes.Mesh003_12.geometry} material={materials['Supergloss Jet Black.051']} />
        <mesh geometry={nodes.Mesh003_13.geometry} material={materials['Supergloss Jet Black.052']} />
        <mesh geometry={nodes.Mesh003_14.geometry} material={materials['Supergloss Jet Black.053']} />
        <mesh geometry={nodes.Mesh003_15.geometry} material={materials['Supergloss Jet Black.054']} />
        <mesh geometry={nodes.Mesh003_16.geometry} material={materials['Supergloss Jet Black.055']} />
        <mesh geometry={nodes.Mesh003_17.geometry} material={materials['Supergloss Jet Black.056']} />
        <mesh geometry={nodes.Mesh003_18.geometry} material={materials['Supergloss Jet Black.057']} />
        <mesh geometry={nodes.Mesh003_19.geometry} material={materials['Supergloss Jet Black.058']} />
        <mesh geometry={nodes.Mesh003_20.geometry} material={materials['Supergloss Jet Black.059']} />
        <mesh geometry={nodes.Mesh003_21.geometry} material={materials['Supergloss Jet Black.060']} />
        <mesh geometry={nodes.Mesh003_22.geometry} material={materials['Supergloss Jet Black.061']} />
        <mesh geometry={nodes.Mesh003_23.geometry} material={materials['Window (Interior/Exterior).002']} />
        <mesh geometry={nodes.Mesh003_24.geometry} material={materials['Supergloss Jet Black.062']} />
        <mesh geometry={nodes.Mesh003_25.geometry} material={materials['Supergloss Jet Black.063']} />
        <mesh geometry={nodes.Mesh003_26.geometry} material={materials['Supergloss Jet Black.064']} />
        <mesh geometry={nodes.Mesh003_27.geometry} material={materials['Supergloss Jet Black.065']} />
      </group>
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -3]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5001.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -5.55]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5002.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -8.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5003.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -10.65]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5004.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -13.2]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5005.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -15.75]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5006.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -18.3]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5007.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -20.85]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5008.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -23.4]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5009.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -25.95]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5010.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -28.5]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5011.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 24.99]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5012.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 22.44]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5013.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 19.89]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5014.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 17.34]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5015.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 14.79]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5016.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 12.24]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5017.geometry} material={materials.Clean_Cement_rhqp1} position={[5, 0, 7.39]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5018.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 27.54]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5019.geometry} material={materials.Clean_Cement_rhqp1} position={[5, 0, 4.71]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5020.geometry} material={materials.Clean_Cement_rhqp1} position={[4.22, 0, -0.97]} rotation={[Math.PI / 2, 0, 0.87]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5021.geometry} material={materials.Clean_Cement_rhqp1} position={[5, 0, 1.83]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5022.geometry} material={materials.Clean_Cement_rhqp1} position={[3.43, 0, 9.9]} rotation={[Math.PI / 2, 0, 2.27]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_00_LOD5023.geometry} material={materials.Clean_Cement_rhqp1} position={[4.85, 0, 8.19]} rotation={[Math.PI / 2, 0, 2.27]} scale={[0, 0.01, 0.01]} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -4.27]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5001.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -6.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5002.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -9.37]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5003.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -11.92]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5004.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -14.47]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5005.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -17.02]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5006.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -19.57]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5007.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -22.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5008.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -24.67]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5009.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, -27.22]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5010.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 23.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5011.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 21.17]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5012.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 18.62]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5013.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 16.07]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5014.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 13.52]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5015.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 10.97]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5016.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 28.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5017.geometry} material={materials.Clean_Cement_rhqp1} position={[3, 0, 26.27]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5018.geometry} material={materials.Clean_Cement_rhqp1} position={[5, 0, 6.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5019.geometry} material={materials.Clean_Cement_rhqp1} position={[5, 0, 3.21]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5020.geometry} material={materials.Clean_Cement_rhqp1} position={[5, 0, 0.56]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5021.geometry} material={materials.Clean_Cement_rhqp1} position={[3.4, 0, -1.93]} rotation={[Math.PI / 2, 0, 0.87]} scale={0.01} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5022.geometry} material={materials.Clean_Cement_rhqp1} position={[4.84, 0, -0.23]} rotation={[Math.PI / 2, 0, 0.87]} scale={[0, 0.01, 0.01]} />
      <mesh geometry={nodes.Aset_street_curbs_M_rhqp1_01_LOD5023.geometry} material={materials.Clean_Cement_rhqp1} position={[4.24, 0, 8.93]} rotation={[Math.PI / 2, 0, 2.27]} scale={0.01} />
      <mesh geometry={nodes._03tr_Var5_LOD5.geometry} material={materials.Boxwood_wfypfa3ha} position={[16.73, 0.7, 6.65]} rotation={[Math.PI / 2, 0, 0]} scale={0.03} />
      <mesh geometry={nodes.Aset_container_decorative_M_ujcgdg1fa_LOD5002.geometry} material={materials.Concrete_Plant_ujcgdg1fa} position={[16.68, 0.07, 6.63]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/final_scene_5.glb')
