/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene1() {
  const { nodes, materials } = useGLTF('/models/scene1.glb')
  return (
    <group dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.mesh_2_lambert5_0001.geometry} material={materials.bench} />
      <mesh castShadow receiveShadow geometry={nodes.kiosk_mesh.geometry} material={materials.kiosk} />
      <mesh castShadow receiveShadow geometry={nodes['��������������_�����'].geometry} material={materials.kiosk_adv} />
      <mesh castShadow receiveShadow geometry={nodes['������009_Material_0001'].geometry} material={materials.Lift} />
      <mesh castShadow receiveShadow geometry={nodes.Model_material0_0_1.geometry} material={materials.energy_1} />
      <mesh castShadow receiveShadow geometry={nodes.Model_material0_0_2.geometry} material={materials.energy_2} />
      <mesh castShadow receiveShadow geometry={nodes.Model_material0_0_3.geometry} material={materials.energy_3} />
      <mesh castShadow receiveShadow geometry={nodes.Model_material0_0_4.geometry} material={materials.energy_4} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002.geometry} material={materials.Wall_2} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_1.geometry} material={materials.Wall_3} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_2.geometry} material={materials.Wall_1} />
      <mesh castShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_3.geometry} material={materials.Roof_3} />
      <mesh castShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_4.geometry} material={materials.Roof_2} />
      <mesh castShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_5.geometry} material={materials.Roof_1} />
      <mesh castShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_6.geometry} material={materials.Corner_1} />
      <mesh castShadow geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_7.geometry} material={materials.Roof_2} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011.geometry} material={materials.house_2_door_2} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_1.geometry} material={materials.house_2_door_1} />
      <mesh castShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_2.geometry} material={materials.house_2_roof} />
      <mesh castShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_3.geometry} material={materials.house_2_roof_trim} />
      <mesh receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_4.geometry} material={materials.house_2_floor_2} />
      <mesh receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_5.geometry} material={materials.house_2_floor_1_top} />
      <mesh receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_6.geometry} material={materials.house_2_floor_3} />
      <mesh receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_7.geometry} material={materials.house_2_floor_1_bot} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_8.geometry} material={materials.house_2_balcony} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_9.geometry} material={materials.house_2_floor_1_mid} />
      <mesh castShadow receiveShadow geometry={nodes.windows_extended.geometry} material={materials.Glass_Placeholder_Windows} />
      <mesh receiveShadow geometry={nodes.Pavement_Main.geometry} material={materials.Pavement_Mat} />
      <mesh receiveShadow geometry={nodes.Pavement_Side.geometry} material={materials.Pavement_Mat} />
      <mesh receiveShadow geometry={nodes.Plane329.geometry} material={materials.Street_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Plane329_1.geometry} material={materials.Bus_Stop_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Curbs.geometry} material={materials.Curbs_Mat} />
      <mesh castShadow receiveShadow geometry={nodes._335j_Var1_LOD5002.geometry} material={materials.Tree_Pot} />
      <mesh castShadow receiveShadow geometry={nodes._z2eb_Var2_LOD5002.geometry} material={materials.Tree_Pot} />
      <mesh receiveShadow geometry={nodes.Cube001.geometry} material={materials.Garden_Concrete} />
      <mesh receiveShadow geometry={nodes.Cube002.geometry} material={materials.Garden_Concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cube026.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cube026_1.geometry} material={materials.Garden_Wood} />
      <mesh receiveShadow geometry={nodes.Cube005.geometry} material={materials.Garden_Concrete} />
      <mesh receiveShadow geometry={nodes.Cube006.geometry} material={materials.Garden_Dirt} />
      <mesh receiveShadow geometry={nodes.Cube029.geometry} material={materials.Garden_Concrete} />
      <mesh receiveShadow geometry={nodes.Cube029_1.geometry} material={materials.Garden_Concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials.Iron_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Cube031.geometry} material={materials.Aluminium_Lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Cube031_1.geometry} material={materials.Aluminium_Lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Cube032.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cube032_1.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cube022.geometry} material={materials.Bench_Stone} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.Garden_Sign} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials.Garden_Sign} />
      <mesh castShadow receiveShadow geometry={nodes.Text002.geometry} material={materials.Bench_Stone} position={[13.48, 0.49, 10.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.36} />
      <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials.Garden_Concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} material={materials.Garden_Concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cube013_2.geometry} material={materials.Garden_Wood} />
      <mesh receiveShadow geometry={nodes.Cube015.geometry} material={materials.Garden_Concrete} />
      <mesh receiveShadow geometry={nodes.Cube016.geometry} material={materials.Garden_Dirt} />
      <mesh castShadow receiveShadow geometry={nodes._335j_Var1_LOD5001.geometry} material={materials.Tree_Pot} />
      <mesh castShadow receiveShadow geometry={nodes._z2eb_Var2_LOD5001.geometry} material={materials.Tree_Pot} />
      <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.Garden_Concrete} />
      <mesh receiveShadow geometry={nodes.Cube016_2.geometry} material={materials.Garden_Concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Cube018.geometry} material={materials.Iron_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Cube019_1.geometry} material={materials.Aluminium_Lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Cube019_2.geometry} material={materials.Aluminium_Lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials.Garden_Sign} />
      <mesh castShadow receiveShadow geometry={nodes.Cube020_1.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cube020_2.geometry} material={materials.Garden_Wood} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={materials.Garden_Sign} />
      <mesh castShadow receiveShadow geometry={nodes.Text001.geometry} material={materials.Bench_Stone} position={[26.51, 0.49, 8.98]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.36} />
      <mesh castShadow receiveShadow geometry={nodes.Cube021.geometry} material={materials.Bench_Stone} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh013.geometry} material={materials.Steel_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh013_1.geometry} material={materials.Adv_Placeholder_1} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh013_2.geometry} material={materials.Aluminium_Lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5.geometry} material={materials.Ashe_Tray} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_1.geometry} material={materials.Trash_Bags} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_2.geometry} material={materials.Case} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_3.geometry} material={materials.Hydrant} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_4.geometry} material={materials.road_sign} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_5.geometry} material={materials.Pole_Yellow} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_6.geometry} material={materials.Parking_Yellow} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_7.geometry} material={materials.Parking_Blue} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_8.geometry} material={materials.Railing} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_9.geometry} material={materials.Trash_can} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_10.geometry} material={materials.bike_stand} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh.geometry} material={materials.Glass_Placeholder_Other} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_1.geometry} material={materials.Metal_Paint_Grey} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_2.geometry} material={materials.Metal_Paint_Black} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_3.geometry} material={materials.Adv_Placeholder_2} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_4.geometry} material={materials.Iron_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_5.geometry} material={materials.Steel_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_6.geometry} material={materials.Aluminium_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_7.geometry} material={materials.Adv_Placeholder_3} />
      <mesh castShadow receiveShadow geometry={nodes.concrete_walk.geometry} material={materials.Concrete_Median} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005_1.geometry} material={materials.bike_stand} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005_2.geometry} material={materials.Aluminium_Lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005_3.geometry} material={materials.Adv_Placeholder_4} />
      <mesh castShadow receiveShadow geometry={nodes.Scooter.geometry} material={materials.Scooter} />
      <mesh castShadow receiveShadow geometry={nodes.concrete_wall.geometry} material={materials.Small_Wall} />
      <mesh castShadow receiveShadow geometry={nodes.Grid002.geometry} material={materials.Water} />
      <mesh castShadow receiveShadow geometry={nodes.Grid002_1.geometry} material={materials.fountain_base} />
      <mesh castShadow receiveShadow geometry={nodes.Grid002_2.geometry} material={materials.Marble_Fountain} />
      <mesh castShadow receiveShadow geometry={nodes.pots.geometry} material={materials.Concrete_Pot} />
      <mesh castShadow receiveShadow geometry={nodes.trees.geometry} material={materials.Tree_Pot} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder026.geometry} material={materials.Aluminium_Lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder026_1.geometry} material={materials.Glass_Placeholder_Other} />
      <mesh castShadow receiveShadow geometry={nodes.lantern_1.geometry} material={materials.Kiosk_Lantern} />
    </group>
  )
}

useGLTF.preload('/models/scene1.glb')
