/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene1.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene1() {
  const { nodes, materials } = useGLTF('/models/scene1.glb')
  return (
    <group dispose={null}>
      <group position={[20.96, 0, 4.7]} rotation={[-Math.PI / 2, 0, -2.79]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[104.41, 39.52, 50.86]}>
            <mesh geometry={nodes.mesh_2_lambert5_0001.geometry} material={materials.bench} position={[-64.56, 1.33, -0.97]} rotation={[0, 0.76, 0]} scale={0.76} />
          </group>
        </group>
      </group>
      <group position={[8.91, 0, 13.86]} rotation={[-Math.PI / 2, 0, 0]} scale={0.84}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-17.01, 216.61, 20.41]} rotation={[-Math.PI / 2, 0, 0.39]} scale={216.42}>
            <mesh geometry={nodes.kiosk_mesh.geometry} material={materials.kiosk} position={[0.09, 0.03, 0.06]} />
          </group>
        </group>
      </group>
      <group position={[17.15, 0.13, 16.53]} rotation={[-Math.PI / 2, 0, 0]} scale={0.53}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 6.8, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[144.91, 144.91, 7.42]}>
            <mesh geometry={nodes['��������������_�����'].geometry} material={materials.kiosk_adv} scale={0.89} />
          </group>
        </group>
      </group>
      <group position={[-8.86, 6.82, 4.52]} rotation={[-Math.PI / 2, 0, -2.63]} scale={0.01}>
        <group position={[47.28, 84.48, 0]} rotation={[Math.PI / 2, -Math.PI / 6, 0]} scale={0.01}>
          <group position={[-0.01, 0, -0.01]}>
            <mesh geometry={nodes['������009_Material_0001'].geometry} material={materials.Lift} position={[6228.25, 3733.85, -18594.04]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 420.7, 900.22]} />
          </group>
        </group>
      </group>
      <group position={[24.31, -1.25, -10.92]} rotation={[-0.24, 0.03, 1.51]} scale={0.42}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[4.37, 0.31, 1.07]}>
              <mesh geometry={nodes.Model_material0_0_1.geometry} material={materials.energy_1} />
              <mesh geometry={nodes.Model_material0_0_2.geometry} material={materials.energy_2} />
              <mesh geometry={nodes.Model_material0_0_3.geometry} material={materials.energy_3} />
              <mesh geometry={nodes.Model_material0_0_4.geometry} material={materials.energy_4} />
            </group>
          </group>
        </group>
      </group>
      <group position={[8, 0.13, -11.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002.geometry} material={materials.Wall_2} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_1.geometry} material={materials.Wall_3} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_2.geometry} material={materials.Wall_1} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_3.geometry} material={materials.Roof_3} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_4.geometry} material={materials.Roof_2} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_5.geometry} material={materials.Roof_1} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_6.geometry} material={materials.Corner_1} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_7.geometry} material={materials.Roof_2} />
      </group>
      <group position={[-10, 0.13, 53]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01}>
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011.geometry} material={materials.house_2_door_2} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_1.geometry} material={materials.house_2_door_1} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_2.geometry} material={materials.house_2_roof} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_3.geometry} material={materials.house_2_roof_trim} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_4.geometry} material={materials.house_2_floor_2} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_5.geometry} material={materials.house_2_floor_1_top} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_6.geometry} material={materials.house_2_floor_3} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_7.geometry} material={materials.house_2_floor_1_bot} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_8.geometry} material={materials.house_2_balcony} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5011_9.geometry} material={materials.house_2_floor_1_mid} />
      </group>
      <mesh geometry={nodes.windows_extended.geometry} material={materials.Glass_Placeholder_Windows} position={[6.34, 2.25, -11.76]} rotation={[Math.PI / 2, 0, 0]} scale={[0.69, 1.14, 1.14]} />
      <mesh geometry={nodes.Curbs.geometry} material={materials.Curbs_Mat} position={[2.76, 0.01, -3.93]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Pavement_Main.geometry} material={materials.Pavement_Mat} position={[-7.64, 0.13, 39]} scale={[2.6, 1.3, 39]} />
      <mesh geometry={nodes.Pavement_Side.geometry} material={materials.Pavement_Mat} position={[5.36, 0.13, -39]} scale={[2.6, 1.3, 39]} />
      <group position={[-1.14, 0.01, -39]} scale={[3.9, 1.3, 39]}>
        <mesh geometry={nodes.Plane329.geometry} material={materials.Street_Mat} />
        <mesh geometry={nodes.Plane329_1.geometry} material={materials.Bus_Stop_Mat} />
      </group>
      <mesh geometry={nodes._335j_Var1_LOD5002.geometry} material={materials.Tree_Pot} position={[13.9, 0.73, 8.82]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes._z2eb_Var2_LOD5002.geometry} material={materials.Tree_Pot} position={[13.89, 0.75, 6.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Garden_Concrete} position={[13.7, 0.45, 4.45]} scale={[0.33, 0.33, 0.4]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Garden_Concrete} position={[16.01, 0.45, 4.45]} scale={[0.33, 0.33, 0.4]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Garden_Wood} position={[16.01, 0.45, 4.45]} scale={[0.33, 0.33, 0.4]} />
      <group position={[16.01, 0.45, 4.45]} scale={[0.33, 0.33, 0.4]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cube005.geometry} material={materials.Garden_Concrete} position={[16.01, 0.45, 4.45]} scale={[0.33, 0.33, 0.4]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.Garden_Dirt} position={[16.01, 0.45, 4.45]} scale={[0.33, 0.33, 0.4]} />
      <group position={[14.03, 0.71, 10.46]} scale={[0.66, 0.58, 0.3]}>
        <mesh geometry={nodes.Cube029.geometry} material={materials.Garden_Concrete} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials.Garden_Concrete} />
      </group>
      <mesh geometry={nodes.Cube008.geometry} material={materials.Iron_Mat} position={[14.21, 0.7, 10.37]} scale={[0.52, 0.46, 0.33]} />
      <group position={[14.21, 0.7, 10.37]} scale={[0.52, 0.46, 0.33]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials.Aluminium_Lantern} />
      </group>
      <group position={[14.03, 0.71, 10.37]} scale={[0.66, 0.58, 0.41]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cube022.geometry} material={materials.Bench_Stone} position={[13.91, 0.85, 10.76]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.03, 0.01, 0.09]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Garden_Sign} position={[14.37, 0.86, 10.45]} rotation={[0, 0, -Math.PI / 2]} scale={[0.07, 0, 0.07]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Garden_Sign} position={[14.37, 0.86, 10.26]} rotation={[0, 0, -Math.PI / 2]} scale={[0.07, 0, 0.07]} />
      <mesh geometry={nodes.Text002.geometry} material={materials.Bench_Stone} position={[13.48, 0.49, 10.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.36} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.Garden_Concrete} position={[26.3, 0.45, 15.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.33, 0.33, 0.4]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.Garden_Concrete} position={[23.98, 0.45, 15.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.33, 0.33, 0.4]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.Garden_Wood} position={[23.98, 0.45, 15.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.33, 0.33, 0.4]} />
      <group position={[23.98, 0.45, 15.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.33, 0.33, 0.4]}>
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cube015.geometry} material={materials.Garden_Concrete} position={[23.98, 0.45, 15.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.33, 0.33, 0.4]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.Garden_Dirt} position={[23.98, 0.45, 15.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.33, 0.33, 0.4]} />
      <mesh geometry={nodes._335j_Var1_LOD5001.geometry} material={materials.Tree_Pot} position={[26.1, 0.73, 10.93]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes._z2eb_Var2_LOD5001.geometry} material={materials.Tree_Pot} position={[26.11, 0.75, 13.45]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.02} />
      <group position={[25.97, 0.71, 9.29]} rotation={[Math.PI, 0, Math.PI]} scale={[0.66, 0.58, 0.3]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials.Garden_Concrete} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials.Garden_Concrete} />
      </group>
      <mesh geometry={nodes.Cube018.geometry} material={materials.Iron_Mat} position={[25.78, 0.7, 9.37]} rotation={[Math.PI, 0, Math.PI]} scale={[0.52, 0.46, 0.33]} />
      <group position={[25.78, 0.7, 9.37]} rotation={[Math.PI, 0, Math.PI]} scale={[0.52, 0.46, 0.33]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.Aluminium_Lantern} />
      </group>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Garden_Sign} position={[25.62, 0.86, 9.29]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.07, 0, 0.07]} />
      <group position={[25.97, 0.71, 9.37]} rotation={[Math.PI, 0, Math.PI]} scale={[0.66, 0.58, 0.41]}>
        <mesh geometry={nodes.Cube020_1.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Garden_Sign} position={[25.62, 0.86, 9.48]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.07, 0, 0.07]} />
      <mesh geometry={nodes.Text001.geometry} material={materials.Bench_Stone} position={[26.51, 0.49, 8.98]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.36} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.Bench_Stone} position={[26.09, 0.85, 8.98]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.03, 0.01, 0.09]} />
      <group position={[22.15, 1.36, 15.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.46}>
        <mesh geometry={nodes.Mesh013.geometry} material={materials.Steel_Mat} />
        <mesh geometry={nodes.Mesh013_1.geometry} material={materials.Adv_Placeholder_1} />
        <mesh geometry={nodes.Mesh013_2.geometry} material={materials.Aluminium_Lantern} />
      </group>
      <group position={[21.88, 0.13, 5.65]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5.geometry} material={materials.Ashe_Tray} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_1.geometry} material={materials.Trash_Bags} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_2.geometry} material={materials.Case} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_3.geometry} material={materials.Hydrant} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_4.geometry} material={materials.road_sign} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_5.geometry} material={materials.Pole_Yellow} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_6.geometry} material={materials.Parking_Yellow} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_7.geometry} material={materials.Parking_Blue} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_8.geometry} material={materials.Railing} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_9.geometry} material={materials.Trash_can} />
        <mesh geometry={nodes.Aset_street__M_uiohfgxfa_LOD5_10.geometry} material={materials.bike_stand} />
      </group>
      <group position={[9, 0.38, 4.5]} rotation={[Math.PI, 0, Math.PI]} scale={0.03}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Glass_Placeholder_Other} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Metal_Paint_Grey} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.Metal_Paint_Black} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.Adv_Placeholder_2} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.Iron_Mat} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.Steel_Mat} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.Aluminium_Mat} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.Adv_Placeholder_3} />
      </group>
      <group position={[-1.19, 0.11, -23.26]} rotation={[0, -Math.PI / 2, 0]} scale={[0.91, 1.14, 0.91]}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials.Billboard_Street} />
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials.Adv_Placeholder_5} />
        <mesh geometry={nodes.Cylinder013_2.geometry} material={materials.Adv_Placeholder_6} />
        <mesh geometry={nodes.Cylinder013_3.geometry} material={materials.Adv_Placeholder_7} />
      </group>
      <mesh geometry={nodes.concrete_walk.geometry} material={materials.Concrete_Median} position={[22.25, 0.12, -1]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[27.19, 7.58, -5.82]} rotation={[Math.PI / 2, 0.27, Math.PI / 2]} scale={[0.23, 0.02, 0.25]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.bike_stand} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials.Adv_Placeholder_4} />
      </group>
      <mesh geometry={nodes.Scooter.geometry} material={materials.Scooter} position={[11.18, 0.11, -10.8]} rotation={[1.44, 0, -Math.PI / 2]} scale={1.38} />
      <mesh geometry={nodes.concrete_wall.geometry} material={materials.Small_Wall_v1} position={[19.73, 0.02, -5.6]} rotation={[0, -Math.PI / 2, 0]} scale={1.44} />
      <group position={[18.78, 1.64, 8.82]} scale={0.45}>
        <mesh geometry={nodes.Grid002.geometry} material={materials.Water} />
        <mesh geometry={nodes.Grid002_1.geometry} material={materials.fountain_base} />
        <mesh geometry={nodes.Grid002_2.geometry} material={materials.Marble_Fountain} />
      </group>
      <mesh geometry={nodes.pots.geometry} material={materials.Concrete_Pot} position={[22.97, 0.27, -0.97]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.trees.geometry} material={materials.Tree_Pot} position={[13.97, 0.92, -0.97]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.03} />
      <group position={[-5.54, 3.24, 13.32]} scale={0.75}>
        <mesh geometry={nodes.Cylinder026.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder026_1.geometry} material={materials.Glass_Placeholder_Other} />
      </group>
      <mesh geometry={nodes.lantern_1.geometry} material={materials.Kiosk_Lantern} position={[26.07, 3.58, 8.64]} rotation={[0, -Math.PI / 2, 0]} scale={[0.44, 1.1, 0.18]} />
    </group>
  )
}

useGLTF.preload('/models/scene1.glb')
