/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene_1_colliderMesh.glb
*/

import React, { useRef, SetStateAction, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { Mesh, Vector3 } from 'three';

const ColliderScene1: React.FC<{
setColliderScene1: React.Dispatch<SetStateAction<Mesh>>
}> = ({setColliderScene1}) => {
  const { nodes, materials } = useGLTF('./models/scene_1_colliderMesh.glb')
  const ref = useRef<Mesh | null>(null);
  setColliderScene1(new Mesh(nodes.scene1_collider.geometry));
  useEffect(() => {
    if(ref.current){
      setColliderScene1(new Mesh(nodes.scene1_collider.geometry));
    }
  },[ref])
  return (
    <></>
  )
}

useGLTF.preload('./models/scene_1_colliderMesh.glb')
export default ColliderScene1;
