/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene1_2() {
  const { nodes, materials } = useGLTF('/models/scene_1_80mb-processed.glb')
  return (
    <group dispose={null}>
      <group position={[15.28, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[104.41, 39.52, 50.86]}>
            <mesh geometry={nodes.mesh_2_lambert5_0.geometry} material={materials.bench} position={[30.02, 7.78, 18.3]} rotation={[0, -0.76, 0]} scale={0.93} />
          </group>
        </group>
      </group>
      <group position={[16.13, 0, 6.76]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[104.41, 39.52, 50.86]}>
            <mesh geometry={nodes.mesh_2_lambert5_0001.geometry} material={materials.bench} position={[30.02, 7.78, 18.3]} rotation={[0, 0.76, 0]} scale={0.93} />
          </group>
        </group>
      </group>
      <group position={[8.91, 0, -5.04]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-17.01, 216.61, 20.41]} rotation={[-Math.PI / 2, 0, 0.39]} scale={216.42}>
            <mesh geometry={nodes.kiosk_mesh.geometry} material={materials.kiosk} position={[0.09, 0.03, 0.06]} />
          </group>
        </group>
      </group>
      <group position={[12.57, 0.13, 10.22]} rotation={[-Math.PI / 2, 0, 0]} scale={0.57}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 6.8, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[144.91, 144.91, 7.42]}>
            <mesh geometry={nodes['��������������_�����'].geometry} material={materials.kiosk_adv} scale={0.89} />
          </group>
        </group>
      </group>
      <group position={[15.56, 0.12, -6.38]} rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[334.78, 1911.03, -0.33]} scale={[245.66, 606.09, 100]}>
            <mesh geometry={nodes['������������������_Mate'].geometry} material={materials.Kiosk_Lantern} />
          </group>
        </group>
      </group>
      <group position={[22.2, 0.12, 16.74]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.2}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[334.78, 1911.03, -0.33]} scale={[245.66, 606.09, 100]}>
            <mesh geometry={nodes['������������������_Mate001'].geometry} material={materials.Kiosk_Lantern} />
          </group>
        </group>
      </group>
      <group position={[11.06, 6.19, 18.14]} rotation={[-Math.PI / 2, 0, -1.06]} scale={0.01}>
        <group position={[47.28, 84.48, 0]} rotation={[Math.PI / 2, -Math.PI / 6, 0]} scale={0.01}>
          <group position={[-0.02, 0, 0]}>
            <group position={[6228.24, 3733.85, -18594.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 420.7, 900.22]}>
              <mesh geometry={nodes['������009_Material_0'].geometry} material={materials.Lift} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-8.86, 6.82, 4.52]} rotation={[-Math.PI / 2, 0, -2.63]} scale={0.01}>
        <group position={[47.28, 84.48, 0]} rotation={[Math.PI / 2, -Math.PI / 6, 0]} scale={0.01}>
          <group position={[-0.01, 0, -0.01]}>
            <group position={[6228.25, 3733.85, -18594.04]} rotation={[-Math.PI / 2, 0, 0]} scale={[200, 420.7, 900.22]}>
              <mesh geometry={nodes['������009_Material_0001'].geometry} material={materials.Lift} />
            </group>
          </group>
        </group>
      </group>
      <group position={[8, 0.13, -11.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002.geometry} material={materials.Wall_2} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_1.geometry} material={materials.Wall_3} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_2.geometry} material={materials.Wall_1} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_3.geometry} material={materials.Roof_3} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_4.geometry} material={materials.Roof_2} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_5.geometry} material={materials.Roof_1} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_6.geometry} material={materials.Corner_1} />
        <mesh geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5002_7.geometry} material={materials.Roof_2} />
      </group>
      <group position={[-10, 0.13, 4]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01}>
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5.geometry} material={materials.house_2_door_2} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_1.geometry} material={materials.house_2_door_1} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_2.geometry} material={materials.house_2_roof} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_3.geometry} material={materials.house_2_roof_trim} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_4.geometry} material={materials.house_2_floor_2} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_5.geometry} material={materials.house_2_floor_1_top} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_6.geometry} material={materials.house_2_floor_3} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_7.geometry} material={materials.house_2_floor_1_bot} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_8.geometry} material={materials.house_2_balcony} />
        <mesh geometry={nodes.Aset_modular__L_ukjsdaidw_LOD5_9.geometry} material={materials.house_2_floor_1_mid} />
      </group>
      <mesh geometry={nodes.windows_extended.geometry} material={materials.Glass_Placeholder} position={[6.34, 2.25, -11.76]} rotation={[Math.PI / 2, 0, 0]} scale={[0.69, 1.14, 1.14]} />
      <mesh geometry={nodes.Curbs.geometry} material={materials.Curbs_Mat} position={[2.76, 0, -3.93]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Pavement_Main.geometry} material={materials.Pavement_Mat} position={[-7.64, 0.13, 39]} scale={[2.6, 1.3, 39]} />
      <mesh geometry={nodes.Pavement_Side.geometry} material={materials.Pavement_Mat} position={[5.36, 0.13, -39]} scale={[2.6, 1.3, 39]} />
      <group position={[-1.14, 0, -39]} scale={[3.9, 1.3, 39]}>
        <mesh geometry={nodes.Plane329.geometry} material={materials.Street_Mat} />
        <mesh geometry={nodes.Plane329_1.geometry} material={materials.Bus_Stop_Mat} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Garden_Concrete} position={[24.61, 0.52, -6.6]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Garden_Concrete} position={[24.61, 0.52, -3.85]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Garden_Wood} position={[24.61, 0.52, -3.85]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.39, 0.48]} />
      <group position={[24.61, 0.52, -3.85]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.39, 0.48]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cube008.geometry} material={materials.Garden_Concrete} position={[24.61, 0.52, -3.85]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Garden_Dirt} position={[24.61, 0.52, -3.85]} rotation={[0, -Math.PI / 2, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes._335j_Var1_LOD5.geometry} material={materials.Tree_Pot} position={[19.42, 0.86, -6.36]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.04} />
      <mesh geometry={nodes._z2eb_Var2_LOD5.geometry} material={materials.Tree_Pot} position={[22.42, 0.87, -6.37]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.03} />
      <group position={[17.47, 0.83, -6.21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.78, 0.69, 0.36]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Garden_Concrete} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.Garden_Concrete} />
      </group>
      <mesh geometry={nodes.Cube005.geometry} material={materials.Iron_Mat} position={[17.57, 0.82, -5.99]} rotation={[0, -Math.PI / 2, 0]} scale={[0.62, 0.55, 0.39]} />
      <group position={[17.57, 0.82, -5.99]} rotation={[0, -Math.PI / 2, 0]} scale={[0.62, 0.55, 0.39]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Lantern_Metal} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.Lantern_Metal} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Garden_Sign} position={[17.47, 1, -5.8]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.08, 0.01, 0.08]} />
      <group position={[17.57, 0.83, -6.21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.78, 0.69, 0.49]}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Garden_Sign} position={[17.7, 1, -5.8]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.08, 0.01, 0.08]} />
      <mesh geometry={nodes.Text.geometry} material={materials.Bench_Stone} position={[17.11, 0.56, -6.86]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.43} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Bench_Stone} position={[17.1, 0.99, -6.35]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.04, 0.01, 0.11]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.Garden_Concrete} position={[13.63, 0.52, 17]} rotation={[0, 1.57, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.Garden_Concrete} position={[13.63, 0.52, 14.25]} rotation={[0, 1.57, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.Garden_Wood} position={[13.63, 0.52, 14.25]} rotation={[0, 1.57, 0]} scale={[0.39, 0.39, 0.48]} />
      <group position={[13.63, 0.52, 14.25]} rotation={[0, 1.57, 0]} scale={[0.39, 0.39, 0.48]}>
        <mesh geometry={nodes.Cube013_1.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cube015.geometry} material={materials.Garden_Concrete} position={[13.63, 0.52, 14.25]} rotation={[0, 1.57, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.Garden_Dirt} position={[13.63, 0.52, 14.25]} rotation={[0, 1.57, 0]} scale={[0.39, 0.39, 0.48]} />
      <mesh geometry={nodes._335j_Var1_LOD5001.geometry} material={materials.Tree_Pot} position={[18.82, 0.86, 16.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
      <mesh geometry={nodes._z2eb_Var2_LOD5001.geometry} material={materials.Tree_Pot} position={[15.82, 0.87, 16.78]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <group position={[20.77, 0.83, 16.61]} rotation={[0, 1.57, 0]} scale={[0.78, 0.69, 0.36]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials.Garden_Concrete} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials.Garden_Concrete} />
      </group>
      <mesh geometry={nodes.Cube018.geometry} material={materials.Iron_Mat} position={[20.67, 0.82, 16.39]} rotation={[0, 1.57, 0]} scale={[0.62, 0.55, 0.39]} />
      <group position={[20.67, 0.82, 16.39]} rotation={[0, 1.57, 0]} scale={[0.62, 0.55, 0.39]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.Aluminium_Lantern} />
      </group>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Garden_Sign} position={[20.77, 1, 16.2]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[0.08, 0.01, 0.08]} />
      <group position={[20.67, 0.83, 16.61]} rotation={[0, 1.57, 0]} scale={[0.78, 0.69, 0.49]}>
        <mesh geometry={nodes.Cube020_1.geometry} material={materials.Garden_Wood} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials.Garden_Wood} />
      </group>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Garden_Sign} position={[20.55, 1, 16.2]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[0.08, 0.01, 0.08]} />
      <mesh geometry={nodes.Text001.geometry} material={materials.Bench_Stone} position={[21.14, 0.56, 17.26]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.43} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.Bench_Stone} position={[21.14, 0.99, 16.75]} rotation={[0, 0, -Math.PI / 2]} scale={[0.04, 0.01, 0.11]} />
      <group position={[36.68, 2.86, 0.08]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.Marble_Fountain} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.Glass_Placeholder} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials.Lantern_Metal} />
        <mesh geometry={nodes.Mesh001_3.geometry} material={materials.Water} />
      </group>
      <mesh geometry={nodes.trash.geometry} material={materials.Trash_Bags} position={[18.24, 0.12, -10.86]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.trash_2.geometry} material={materials.Trash_Bags} position={[7.07, 0.12, 18.77]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.02} />
      <group position={[-5.56, 0.13, -9.74]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Aset_other_various_M_ujyvbgofa_LOD5001.geometry} material={materials.Parking_Yellow} />
        <mesh geometry={nodes.Aset_other_various_M_ujyvbgofa_LOD5001_1.geometry} material={materials.Parking_Blue} />
      </group>
      <mesh geometry={nodes.railing.geometry} material={materials.Railing} position={[2.99, 0.12, -13.35]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.poles_yellow.geometry} material={materials.Pole_Yellow} position={[-5.57, 0.13, -11.89]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.hydrant.geometry} material={materials.Hydrant} position={[3.4, 0.13, 18.65]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[-1.19, 0.11, 22.76]} rotation={[0, Math.PI / 2, 0]} scale={[0.91, 1.14, 0.91]}>
        <mesh geometry={nodes.Cylinder030.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cylinder030_1.geometry} material={materials.Adv_Placeholder_5} />
        <mesh geometry={nodes.Cylinder030_2.geometry} material={materials.Adv_Placeholder_6} />
        <mesh geometry={nodes.Cylinder030_3.geometry} material={materials.Adv_Placeholder_7} />
      </group>
      <group position={[26.62, 6.8, -4.68]} rotation={[Math.PI / 2, -1.3, -Math.PI / 2]} scale={[-4.09, -0.15, -0.07]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.Adv_Placeholder_4} />
      </group>
      <mesh geometry={nodes.Bike_stand.geometry} material={materials.bike_stand} position={[9.77, 0.13, 3.43]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[7.98, 1.36, 9.62]} rotation={[Math.PI / 2, 0, 0]} scale={0.46}>
        <mesh geometry={nodes.Mesh013.geometry} material={materials.Steel_Mat} />
        <mesh geometry={nodes.Mesh013_1.geometry} material={materials.Adv_Placeholder_1} />
        <mesh geometry={nodes.Mesh013_2.geometry} material={materials.Aluminium_Lantern} />
      </group>
      <mesh geometry={nodes.traffic_Signal_Control.geometry} material={materials.Case} position={[4.95, 0.13, -10.85]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.No_Parking_Sign.geometry} material={materials.road_sign} position={[4, 0.13, -2.75]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Ashe_Tray.geometry} material={materials.Ashe_Tray} position={[8.67, 0.13, 7.63]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[9, 0.38, 4.5]} rotation={[Math.PI, 0, Math.PI]} scale={0.03}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Glass_Placeholder} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Metal_Paint_Grey} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.Metal_Paint_Black} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.Adv_Placeholder_2} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.Iron_Mat} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.Steel_Mat} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials.Aluminium_Mat} />
        <mesh geometry={nodes.Mesh_7.geometry} material={materials.Adv_Placeholder_3} />
      </group>
      <group position={[-1.19, 0.11, -23.26]} rotation={[0, -Math.PI / 2, 0]} scale={[0.91, 1.14, 0.91]}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials.Adv_Placeholder_5} />
        <mesh geometry={nodes.Cylinder013_2.geometry} material={materials.Adv_Placeholder_6} />
        <mesh geometry={nodes.Cylinder013_3.geometry} material={materials.Adv_Placeholder_7} />
      </group>
      <mesh geometry={nodes.Pot003.geometry} material={materials.Concrete_Pot} position={[25.43, 0.13, 9.58]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Pot_Tree003.geometry} material={materials.Tree_Pot} position={[25.43, 0.65, 9.58]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.Pot002.geometry} material={materials.Concrete_Pot} position={[25.43, 0.13, 12.04]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Pot_Tree002.geometry} material={materials.Tree_Pot} position={[25.43, 0.65, 12.04]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.Pot001.geometry} material={materials.Concrete_Pot} position={[25.43, 0.13, 14.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Pot_Tree001.geometry} material={materials.Tree_Pot} position={[25.43, 0.65, 14.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.Pot.geometry} material={materials.Concrete_Pot} position={[25.43, 0.13, 16.95]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Pot_Tree.geometry} material={materials.Tree_Pot} position={[25.43, 0.65, 16.95]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
      <mesh geometry={nodes.Pot005.geometry} material={materials.Concrete_Pot} position={[12.13, 0.13, 17.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Pot_Tree005.geometry} material={materials.Tree_Pot} position={[12.13, 0.65, 17.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.Pot004.geometry} material={materials.Concrete_Pot} position={[5.02, 0.13, 17.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Pot_Tree004.geometry} material={materials.Tree_Pot} position={[5.02, 0.65, 17.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <group position={[-5.54, 3.24, 13.32]} scale={0.75}>
        <mesh geometry={nodes.Cylinder026.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder026_1.geometry} material={materials.Glass_Placeholder} />
      </group>
      <group position={[-5.54, 3.24, 1.14]} scale={0.75}>
        <mesh geometry={nodes.Cylinder009.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials.Glass_Placeholder} />
      </group>
      <group position={[-3.34, 8.08, -10.86]} scale={[0.72, 0.79, 1.26]}>
        <mesh geometry={nodes.Cylinder025.geometry} material={materials.Glass_Placeholder} />
        <mesh geometry={nodes.Cylinder025_1.geometry} material={materials.Aluminium_Lantern} />
      </group>
      <group position={[-5.54, 3.24, 31.54]} scale={0.75}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Glass_Placeholder} />
      </group>
      <group position={[-5.54, 3.24, 44.08]} scale={0.75}>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials.Glass_Placeholder} />
      </group>
      <group position={[-5.54, 3.24, -35.75]} scale={0.75}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials.Glass_Placeholder} />
      </group>
      <group position={[-5.54, 3.24, -48.53]} scale={0.75}>
        <mesh geometry={nodes.Cylinder008.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials.Glass_Placeholder} />
      </group>
      <group position={[-5.54, 3.24, 56.98]} scale={0.75}>
        <mesh geometry={nodes.Cylinder010.geometry} material={materials.Aluminium_Lantern} />
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials.Glass_Placeholder} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/scene_1_80mb-processed.glb')
