/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// @ts-nocheck

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export function Scene1() {
  const { nodes, materials } = useGLTF('/models/scene_1_comp.glb');
  return (
    <group dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Pavement_Right.geometry}
        material={materials.Pavement_Mat}
        position={[15.77, 0.13, 0]}
        scale={[13, 1.3, 39]}
      />
      <group position={[-1.14, 0, 0]} scale={[3.9, 1.3, 39]}>
        <mesh receiveShadow geometry={nodes.Plane.geometry} material={materials.Street_Mat} />
        <mesh receiveShadow geometry={nodes.Plane_1.geometry} material={materials.Bus_Stop_Mat} />
      </group>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Pavement_Left.geometry}
        material={materials.Pavement_Mat}
        position={[-7.64, 0.13, 0]}
        scale={[2.6, 1.3, 39]}
      />
      <group position={[9, 0.34, 4.5]} rotation={[Math.PI, 0, Math.PI]} scale={0.03}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Glass} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_1.geometry} material={materials.Metal_Paint_Grey} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_2.geometry} material={materials.Metal_Paint_Black} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_3.geometry} material={materials.ADV_poster} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_4.geometry} material={materials.Iron_Mat} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_5.geometry} material={materials.Steel_Mat} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_6.geometry} material={materials.Aluminium_Mat} />
      </group>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Curbs.geometry}
        material={materials.Curbs_Mat}
        position={[2.76, 0, -3.93]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.01}
      />
      <group position={[8, 0.13, -11.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5001.geometry}
          material={materials.Wall_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5001_1.geometry}
          material={materials.Roof_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5001_2.geometry}
          material={materials.Corner_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5001_3.geometry}
          material={materials.Wall_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5001_4.geometry}
          material={materials.Wall_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5001_5.geometry}
          material={materials.Roof_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_building_combined_M_vdipcdadw_00_LOD5001_6.geometry}
          material={materials.Roof_2}
        />
      </group>
      <group position={[-10, 2.63, -12]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009.geometry}
          material={materials.house_2_floor_1_mid}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_1.geometry}
          material={materials.house_2_door_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_2.geometry}
          material={materials.house_2_door_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_3.geometry}
          material={materials.house_2_roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_4.geometry}
          material={materials.house_2_roof_trim}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_5.geometry}
          material={materials.house_2_floor_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_6.geometry}
          material={materials.house_2_floor_1_top}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_7.geometry}
          material={materials.house_2_floor_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_8.geometry}
          material={materials.house_2_floor_1_bot}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Aset_modular_urban_M_ukjsefadw_03_LOD5009_9.geometry}
          material={materials.house_2_balcony}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/scene_1_comp.glb');
