/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// @ts-nocheck

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export function TestMesh() {
  const { nodes, materials } = useGLTF('./models/testMeshes.glb');
  return (
    <group dispose={null}>
      <mesh receiveShadow castShadow geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh receiveShadow castShadow geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh receiveShadow castShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh receiveShadow castShadow geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
      <mesh receiveShadow castShadow geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} />
      <mesh receiveShadow castShadow geometry={nodes.Text.geometry} material={nodes.Text.material} />
      <mesh receiveShadow castShadow geometry={nodes.Text001.geometry} material={nodes.Text001.material} />
      <mesh receiveShadow castShadow geometry={nodes.Text002.geometry} material={nodes.Text002.material} />
      <mesh receiveShadow castShadow geometry={nodes.Text003.geometry} material={nodes.Text003.material} />
      <mesh receiveShadow castShadow geometry={nodes.Text004.geometry} material={nodes.Text004.material} />
      <mesh receiveShadow castShadow geometry={nodes.Cube005.geometry} material={materials.transparent} />
      <mesh receiveShadow castShadow geometry={nodes.Text005.geometry} material={nodes.Text005.material} />
    </group>
  );
}

useGLTF.preload('./models/testMeshes.glb');
